# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([
    [1, 2, 3],
    [4, 5, 5.5]
])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.dtype, a1.size, type(a1)

((3,), dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.dtype, a2.size, type(a2)

((2, 3), dtype('float64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.dtype, a3.size, type(a3)

((2, 3, 3), dtype('int32'), 18, numpy.ndarray)

In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
sample_array = pd.DataFrame(a2)
sample_array

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  5.5

In [11]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Create an array within a range of 0 and 100 with step 3
samp_array = np.arange(0, 100, 3)
samp_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [16]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size=(7, 2))
random_array

array([[4, 3],
       [5, 0],
       [8, 5],
       [1, 6],
       [9, 1],
       [1, 9],
       [9, 6]])

In [17]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_1 = np.random.random((3, 5))
random_array_1

array([[0.2237948 , 0.00326319, 0.25481773, 0.01012189, 0.61583897],
       [0.00550568, 0.81847655, 0.05934133, 0.04328825, 0.81710767],
       [0.52921443, 0.03829689, 0.67255736, 0.3939787 , 0.26871798]])

In [20]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_3 = np.random.random((4, 6))
random_array_3

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

No the numbers in the array are different. The random seed is set to 42 and as numpy doesn't really have random numbers and has pseudo random numbers so eventually along with the no of times you run the cell, we'll reach an array with the same combination of numbers

In [22]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_4 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(random_array_4)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Find the 0'th index of the latest array you created
random_array_4[0]

array([3, 1, 4, 2, 8, 4, 2])

In [28]:
random_array_4

array([[3, 1, 4, 2, 8, 4, 2],
       [6, 6, 4, 6, 2, 2, 4],
       [8, 7, 9, 8, 5, 2, 5]])

In [37]:
# Get the first 2 rows of latest array you created
random_array_4[:2, :7,]

array([[3, 1, 4, 2, 8, 4, 2],
       [6, 6, 4, 6, 2, 2, 4]])

In [38]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_4[:2, :2]

array([[3, 1],
       [6, 6]])

In [39]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_5 = np.random.randint(0, 10, size=(3, 5))
ones_new = np.ones((3, 5))

In [40]:
# Add the two arrays together
ones_new + random_array_5

array([[ 8., 10.,  9.,  9.,  1.],
       [ 9.,  7.,  9.,  8.,  1.],
       [ 8.,  8.,  3.,  1.,  8.]])

In [42]:
# Create another array of ones of shape (5, 3)
ones_new_t = ones_new.T
ones_new_t

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
# Try add the array of ones and the other most recent array together
ones_new_t + ones_new

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

Transpose one of the matrix to make their dimensions same

In [44]:
# Create another array of ones of shape (3, 5)
ones_new

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
# Subtract the new array of ones from the other most recent array
ones_new - ones_new_t

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [46]:
# Multiply the ones array with the latest array
ones_new * random_array_5

array([[7., 9., 8., 8., 0.],
       [8., 6., 8., 7., 0.],
       [7., 7., 2., 0., 7.]])

In [50]:
# Take the latest array to the power of 2 using '**'
random_array_5 ** 2

array([[49, 81, 64, 64,  0],
       [64, 36, 64, 49,  0],
       [49, 49,  4,  0, 49]])

In [25]:
# Do the same thing with np.square()
np.square(random_array_5)

In [51]:
# Find the mean of the latest array using np.mean()
np.mean(random_array_5)

5.6

In [52]:
# Find the maximum of the latest array using np.max()
np.max(random_array_5)

9

In [53]:
# Find the minimum of the latest array using np.min()
np.min(random_array_5)

0

In [54]:
# Find the standard deviation of the latest array
np.std(random_array_5)

3.179098404684364

In [55]:
# Find the variance of the latest array
np.var(random_array_5)

10.106666666666667

In [57]:
# Reshape the latest array to (3, 5, 1)
random_array_6 = random_array_5.reshape(3, 5, 1)

In [59]:
# Transpose the latest array
random_array_6.T

array([[[7, 8, 7],
        [9, 6, 7],
        [8, 8, 2],
        [8, 7, 0],
        [0, 0, 7]]])

What does the transpose do?
reverse the order of the dimensions of a matix

In [62]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand_arr = np.random.randint(10, size=(3, 3))
rand_arr_1 = np.random.randint(10, size=(3, 2))

In [63]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_arr, rand_arr_1)

array([[72, 44],
       [24, 24],
       [61, 43]])

In [64]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand_arr_2 = np.random.randint(10, size=(4, 3))
rand_arr_3 = np.random.randint(10, size=(4, 3))

In [65]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_arr_2, rand_arr_3)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?
transpose the matrix

In [66]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(rand_arr_2, rand_arr_3.T)

array([[ 22,  24,  32,  34],
       [ 69, 108,  96, 111],
       [ 87, 129, 111, 161],
       [ 24,  48,  24,  56]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Because the requirement for a dot product of occur is that the two inner dimensions of the matrix need to be the same. (X * Y and Y * Z)

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [67]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand_arr_4 = np.random.randint(10, size=(3, 2))
rand_arr_5 = np.random.randint(10, size=(3, 2))

In [68]:
# Compare the two arrays with '>'
rand_arr_4 > rand_arr_5

array([[False,  True],
       [ True,  True],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [69]:
# Compare the two arrays with '>='
rand_arr_4 >= rand_arr_5

array([[False,  True],
       [ True,  True],
       [False,  True]])

In [71]:
# Find which elements of the first array are greater than 7
rand_arr_4 > 7

array([[False, False],
       [False,  True],
       [False,  True]])

In [73]:
# Which parts of each array are equal? (try using '==')
rand_arr_4 == rand_arr_5

array([[False, False],
       [False, False],
       [False, False]])

In [74]:
# Sort one of the arrays you just created in ascending order
np.sort(rand_arr_4)

array([[4, 5],
       [3, 9],
       [6, 8]])

In [75]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand_arr_4)

array([[0, 1],
       [0, 1],
       [0, 1]], dtype=int64)

In [78]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand_arr_4)

3

In [77]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand_arr_4)

2

In [79]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rand_arr_4, axis=1)

array([1, 1, 1], dtype=int64)

In [81]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(rand_arr_4, axis=0)

array([1, 0], dtype=int64)

In [82]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-1.34938997, -1.01907279,  0.12701224, -1.24944372,  1.94511561],
       [-0.15333646, -0.90698723, -0.81735416, -0.48312268, -0.56982835],
       [-2.09159967,  1.26374053, -0.01548334, -0.02737645,  0.81787351]])

In [84]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.